# Part-2 Operation in Numpy

In [3]:
import numpy as np

In [5]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [7]:
a+1 # adding 1 to every element ( scalar addition)

array([2, 3, 4, 5])

In [8]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [9]:
b = np.ones(4)+1
b

array([2., 2., 2., 2.])

In [10]:
a-b

array([-1.,  0.,  1.,  2.])

In [11]:
a*b

array([2., 4., 6., 8.])

In [12]:
c = np.diag([1,2,3,4])
c

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [14]:
print(c*c)
print('***************')

print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
***************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [15]:
a = np.array([1,2,3,4])
b = np.array([5,2,2,4])
a == b

array([False,  True, False,  True])

In [16]:
a > b

array([False, False,  True, False])

In [17]:
(a>b).dtype

dtype('bool')

In [22]:
a = np.arange(1,5)
b = np.array([5,2,2,4])
c = np.array([1,2,3,4])
np.array_equal(a,b)

False

In [23]:
np.array_equal(a,c)

True

In [24]:
a = np.array([1,1,0,0],dtype=bool)
b = np.array([1,0,1,0],dtype=bool)

np.logical_or(a,b)

array([ True,  True,  True, False])

In [25]:
np.logical_and(a,b)

array([ True, False, False, False])

In [26]:
a = np.arange(5)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [27]:
np.log(a)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [28]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

#  Shape mismatch

In [29]:
a = np.arange(4)
a + np.array([1,2])

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

##  basic reductions

In [31]:
x = np.array([1,2,3,4])
np.sum(x)

10

In [32]:
x = np.array([[1,1],[2,2]])
x

array([[1, 1],
       [2, 2]])

In [33]:
x.sum(axis=0)

array([3, 3])

In [34]:
x.sum(axis=1)

array([2, 4])

### Other reductions

In [35]:
x = np.array([1,2,3,6,5])

In [36]:
x.min()

1

In [37]:
x.max()

6

In [42]:
x.argmin() # index of the minimum element

0

In [43]:
x.argmax() # index of the maximum element

3

### Logical operations 

In [44]:
np.all([True,True,False])

False

In [45]:
np.any([True,True,False])

True

In [49]:
np.all([1,2,-1])

True

In [50]:
a = np.zeros([50,50])
np.any(a != 0)

False

In [51]:
np.all(a==a)

True

In [55]:
a = np.array([1,2,3,2])
b = np.array([2,2,3,2])
c = np.array([6,4,4,5])
((a <= b) & (b <= c)).all()

True

## Statistics 

In [56]:
x = np.array([1,2,3,1])
y = np.array([[1,2,3],[5,6,1]])
x.mean()

1.75

In [59]:
np.median(x)

1.5

In [61]:
np.median(y, axis=-1)

array([2., 5.])

In [63]:
x.std()

0.82915619758885

# Broad Casting 

In [118]:
a = np.tile(np.arange(0,40,10),(3,1))
'''Here we have the array np.arange(0,40,10) and we replicate it 
3 times in the columns and 1 time in the rows using tile function'''
print(a)
print('********************')
a=a.T
print(a)

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]
********************
[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


In [119]:
a = np.tile(np.arange(0,40,10),(3,2))
print(a)
print('********************')
a=a.T
print(a)

[[ 0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30]]
********************
[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]
 [ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


In [120]:
b = np.array([0,1,2])
b

array([0, 1, 2])

In [121]:
a+b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32],
       [ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [122]:
a = np.tile(np.arange(0,40,10),(3,1))
print(a)
print('********************')
a=a.T
print(a)

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]
********************
[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


In [123]:
a+b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [124]:
a = np.array([0,10,20,30])

In [125]:
a.shape

(4,)

In [129]:
a = a[:, np.newaxis] # convert from 1D to 2D array (adds dimension)
print(a.shape)
print(a)

(1, 1, 4)
[[[ 0 10 20 30]]]


In [130]:
a = a.T
print(a)

[[[ 0]]

 [[10]]

 [[20]]

 [[30]]]


In [131]:
a+b

array([[[ 0,  1,  2]],

       [[10, 11, 12]],

       [[20, 21, 22]],

       [[30, 31, 32]]])

#  Array Shape Manipulation

In [132]:
a = np.array([[1,2,3],[4,5,6]])
a.ravel() # convert array to 1D

array([1, 2, 3, 4, 5, 6])

In [133]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [134]:
a.T.ravel()

array([1, 4, 2, 5, 3, 6])

In [135]:
print(a.shape)

(2, 3)


In [136]:
print(a)

[[1 2 3]
 [4 5 6]]


In [137]:
b = a.ravel()
print(b)

[1 2 3 4 5 6]


In [138]:
np.shares_memory(a,b)

True

In [139]:
b = b.reshape((2,3))
b

array([[1, 2, 3],
       [4, 5, 6]])

# Dimension Shuffeling

In [142]:
a = np.arange(4*3*2).reshape(4,3,2)
a.shape

(4, 3, 2)

In [143]:
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [144]:
a[0,2,1]

5

### Resizing

In [145]:
a = np.arange(4)
a.resize((8,))
a

array([0, 1, 2, 3, 0, 0, 0, 0])

In [147]:
b = a
a.resize((4,)) # can't resize cause b is sharing memory

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

### Sorting Data 

In [150]:
a = np.array([[5,4,6],[2,3,2]])
b = np.sort(a,axis=1)
b

array([[4, 5, 6],
       [2, 2, 3]])

In [151]:
np.shares_memory(a,b)

False

In [149]:
a.sort(axis=1) # if we do this the sorted value is stored in a
a

array([[4, 5, 6],
       [2, 2, 3]])

In [154]:
a = np.array([4,3,1,2])
j = np.argsort(a)
'''here it will return the index of the elemnts where that element is present
before sorting'''
j

array([2, 3, 1, 0], dtype=int64)

In [155]:
a[j]

array([1, 2, 3, 4])

# part-2 End 