# The Numpy basics part-1 

In [108]:
# Import the numpy
import numpy as np
# make a numpy array
a = np.array([0,1,2,3])
print(a)

[0 1 2 3]


In [10]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [11]:
# Check how nuch time it takes in general = 277um
L = range(1000)
%timeit [i**2 for i in L]

277 µs ± 5.14 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [15]:
'''# with numpy it takes less time almost 200 times less
(cause of vectorisation and such in numpy)'''
a = np.arange(1000)
%timeit a**2

1.31 µs ± 3.18 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [16]:
a = np.array([0,1,2,3])

In [17]:
a

array([0, 1, 2, 3])

In [18]:
# get the dimension of the array
a.ndim

1

In [19]:
'''get the shape of the array 
(if its 1D/vector then the no. of elements in the vector)'''
a.shape

(4,)

In [20]:
# get the first element of the array shape
len(a)

4

In [21]:
# make a 2D array
b = np.array([[1,2,3],[4,5,6]])

In [40]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
b.ndim

2

In [42]:
b.shape

(2, 3)

In [43]:
len(b)

2

In [44]:
# making a 3D array
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [45]:
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [30]:
c.ndim

3

In [32]:
c.shape

(2, 2, 2)

In [34]:
d = np.arange(1,10,2) # from 1 to 10 with a step of 2
d

array([1, 3, 5, 7, 9])

In [37]:
e = np.linspace(0,1,6) # from 0 to 1 in 6 equal value range
e

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [38]:
f = np.ones((3,3)) # create a 2D array where all values are 1

In [39]:
f

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [46]:
g = np.zeros((3,3)) # create a 2D array with all values as zero
g

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [47]:
h = np.eye(3) # create a identity matrix of n dim
h

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [48]:
i = np.diag([1,2,3,4]) # a diagonal matrix with all other values zero
i

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [49]:
np.diag(i)

array([1, 2, 3, 4])

# Using Randoms 

In [109]:
# Using random to create an array
a = np.random.rand(4) # return array of size 4 (uniformly distributed)
a

array([0.41030507, 0.496651  , 0.55533752, 0.8344595 ])

In [59]:
b = np.random.randn(4) # return 'standard normal numbers'
b

array([ 1.27072532,  0.06194945, -0.85969836,  2.20364142])

In [61]:
c = np.arange(10, dtype='float64') # to change data type
c

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [62]:
d = np.array([1+2j, 2+4j])
print(d)
print(d.dtype)

[1.+2.j 2.+4.j]
complex128


In [63]:
e = np.array(['Ram','Robert','Rahim'])
e.dtype

dtype('<U6')

In [64]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
print(a[5])

5


In [67]:
a = np.diag([1,2,3,4])
print(a)
print(a[2,2])

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
3


In [68]:
a[2,1] = 5
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 5, 3, 0],
       [0, 0, 0, 4]])

In [70]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
a[1:5]

array([1, 2, 3, 4])

In [74]:
a[1:8:2]

array([1, 3, 5, 7])

In [76]:
a = np.arange(10)
a[5:] = 10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [78]:
b = np.arange(5)
a[5:] = b[::-1]
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

# Copies and views

In [79]:
a =np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
b = a[::2]
b

array([0, 2, 4, 6, 8])

In [87]:
np.shares_memory(a,b)
# cause of this if we change b a will also change

True

In [88]:
b[1] = 3
b

array([0, 3, 4, 6, 8])

In [89]:
a

array([0, 1, 3, 3, 4, 5, 6, 7, 8, 9])

In [90]:
# so if u don't want to share the memory use 'copy' function
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [93]:
b = a.copy()
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [95]:
np.shares_memory(a,b)

False

In [96]:
b[2] = 3
print(b)
print(a)

[0 1 3 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


# using mask

In [97]:
a = np.random.randint(0,20,15) # random no. between 0 and 20 and 15 such no.
a

array([18,  5,  0,  8,  8, 13, 13, 10, 17, 15,  9,  8, 10, 18, 18])

In [98]:
mask = (a % 2 == 0)

In [100]:
extract_from_a = a[mask] # mask don't create views
extract_from_a

array([18,  0,  8,  8, 10,  8, 10, 18, 18])

In [101]:
np.shares_memory(a,extract_from_a)

False

In [102]:
a[mask] = -1
a

array([-1,  5, -1, -1, -1, 13, 13, -1, 17, 15,  9, -1, -1, -1, -1])

In [105]:
a = np.arange(0,100,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [106]:
a[[2,3,2,4,2]]

array([20, 30, 20, 40, 20])

In [107]:
a[[9,7]] = -1
a

array([ 0, 10, 20, 30, 40, 50, 60, -1, 80, -1])

# Part 1 end 